Code College/Code College/Controllers/ExerciseController.cs
using Code_College.Models;
using System.Linq;
using System.Web.Mvc;

namespace Code_College.Controllers
{
    public class ExerciseController : Controller
    {
        private static ExDBEntities ExDB = new ExDBEntities();

        // GET: Exercise
        public ActionResult Index(int id = 1)
        {
            Exercise CurrentExercise = ExDB.Exercises.Where(x => x.ExID == id).FirstOrDefault();

            // Loads exercise data into the ViewBag for the view to display
            ViewBag.ExID = CurrentExercise.ExID;
            ViewBag.Title = CurrentExercise.ExTitle + " - Code College";
            ViewBag.ExerciseTitle = CurrentExercise.ExTitle;
            ViewBag.Desc = CurrentExercise.ExDescription;
            ViewBag.ExerciseID = CurrentExercise.ExID;
            ViewBag.CodeTemplate = CurrentExercise.ExCodeTemplate ?? "";
            ViewBag.AppendCode = CurrentExercise.ExAppendCode ?? "";

            return View();
        }
    }
}

Code College/Code College/Controllers/LoginController.cs
using System.Web.Mvc;

namespace Code_College.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

Code College/Code College/Views/Exercise/Exercise.cshtml
@using System.Web.Optimization;
@using System.Data.Entity;
@using Code_College.Models;

@{ 
    ExDBEntities ExDB = new ExDBEntities();
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render();
    @Scripts.Render();

    <script type="text/javascript">
        $(function () {
            var Console = $.connection.ConsoleHub;

            Console.client.UpdateConsole = function (ConsoleOutput) {

            };

            $.connection.hub.start().done(function () {

            });
        });
    </script>
</head>
<body>
    <div>
    </div>
</body>
</html>

Code College/Code College/Views/Exercise/Index.cshtml
@using System.Web.Optimization;
@using Code_College.Models;

@{
    bool Redirect = false;
    int ExerciseID = ViewBag.ExID;
    UserDBEntities UserDB = new UserDBEntities();

    if (Request.Cookies.AllKeys.Contains("CCUserAuth"))
    {
        HttpCookie Cookie = Request.Cookies["CCUserAuth"];

        if (!Account.VerifyCookie(Cookie))
        {
            Redirect = true;
        }
        else
        {
            string Username = Cookie.Values["Username"];
            string Password = Cookie.Values["Password"];

            ViewBag.Username = Username;
            ViewBag.Password = Password;

            User User = UserDB.Users.Where(x => x.Username == Username).FirstOrDefault();

            if (ExerciseID > User.UserLevel)
            {
                Redirect = true;
            }
        }
    }
    else
    {
        Redirect = true;
    }
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Code College, Exercise, Learn Programming, Learn Lua, Lua, Development, Code, @ViewBag.ExerciseTitle" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <title>@ViewBag.Title</title>

    @Styles.Render("~/bundles/editorcss")
    @Scripts.Render("~/bundles/editorjs")

    @Scripts.Render("~/bundles/js")

    <style>
        #Console {
            background: #1A1A1A;
            height: 30px;
            width: 300px;
            border-radius: 2em;
            border: none;
            color: #A2A2A2;
            padding-left: 1.5em;
            outline: none;
            box-shadow: 0 4px 6px -5px hsl(0, 0%, 40%), inset 0px 4px 6px -5px hsl(0, 0%, 2%);
        }

        .ExTitle {
            font-family: 'Roboto', sans-serif;
            font-size: x-large;
            text-align: center;
            color: white;
            padding-top: 15px;
        }

        .ExDesc {
            font-family: Arial;
            color: #FFFFFF;
            padding-top: 10px;
            padding-bottom: 30px;
        }

        .Message {
            color: white;
        }

        .Copyright {
            color: white;
            text-align: center;
            font-family: 'Roboto', sans-serif;
            font-size: small;
        }
    </style>

    <script>
        var Redirect = "@Redirect";

        if (Redirect === "True") {
            window.location = "@Url.Action("Index", "Login")";
        }

        function UpdateConsole()
        {
            var Submission = new Object();

            Submission.id = @ViewBag.ExerciseID;
            Submission.username = "@ViewBag.Username";
            Submission.password = "@ViewBag.Password";
            Submission.code = editor.getValue() + "@ViewBag.AppendCode";

            $.ajax({
                url: '/api/code',
                type: 'POST',
                dataType: 'json',
                data: Submission,
                success: function (data, textStatus, xhr) {
                    console.log(data);
                    document.getElementById("Console").value = data;
                    CodeCorrect(data);
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log('Error in Operation');
                    console.log(xhr);
                    console.log(textStatus);
                    console.log(errorThrown);
                }
            });
        }

        function CodeCorrect (ConsoleOutput)
        {
            if (ConsoleOutput === "Sorry, that was incorrect. Please, read the task and try again.") {
                document.getElementsByClassName("Message")[0].innerHTML = "Incorrect, your code does not adhere to the task set, sorry.";

                document.getElementById("Console").style['background'] = 'red';
            }
            else if (ConsoleOutput.startsWith('Interpreter:')) {
                document.getElementsByClassName("Message")[0].innerHTML = "Incorrect, you have a syntax error in your code.";

                document.getElementById("Console").style['background'] = 'red';
            }
            else {
                document.getElementsByClassName("Message")[0].innerHTML = "Correct!";
                document.getElementById("button").onclick = NextExercise;
                document.getElementById("button").innerHTML = "Next Exercise";

                document.getElementById("Console").style['background'] = 'green';
            }
        }

        function NextExercise() {
            var ExerciseID = @ViewBag.ExID;
            ExerciseID++;

            window.location = "@Url.Action("Index", "Exercise")?id=" + ExerciseID;
        }
    </script>
</head>

<body style="background-color: black;">
    <div class="ExTitle" style="height: 50px; background-color: #06D995">@ViewBag.ExerciseTitle</div>

    <div class="ExDesc">
        @ViewBag.Desc
    </div>

    <div>
        <textarea id="Code" name="code" value="" style="width: 300px; height: 65px"></textarea>
        <button id="button" onclick="UpdateConsole()">Submit</button>
    </div>

    <div>
        Console:
        <br />@Html.TextBox("Console", null, new { id = "Console" })<br />
    </div>

    <div class="Message"></div>

    <script>
        var CodeTemplate = "@ViewBag.CodeTemplate";
        var Temp
        var editor = CodeMirror.fromTextArea(document.getElementById("Code"), {
            mode: "lua",
            lineNumbers: true,
            matchBrackets: true,
            theme: "night"
        });

        while (CodeTemplate != Temp) {
            Temp = CodeTemplate;

            CodeTemplate = CodeTemplate.replace("&quot;", "\"");
        }

        editor.getDoc().setValue(CodeTemplate);
    </script>

    <div class="Copyright">
        <p>Copyright © 2015 Code College. All Rights Reserved</p>
    </div>
</body>
</html>